'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace SpectronServiceReference
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="SpectronServiceReference.ISpectron")>  _
    Public Interface ISpectron
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISpectron/configure_653x", ReplyAction:="http://tempuri.org/ISpectron/configure_653xResponse")>  _
        Function configure_653x(ByVal deviceName As String, ByVal trigger As String, ByVal clock As String, ByVal total_cycles As Integer) As System.IntPtr
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISpectron/initialize_data", ReplyAction:="http://tempuri.org/ISpectron/initialize_dataResponse")>  _
        Sub initialize_data(ByVal total_cycles As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISpectron/transpose_data", ReplyAction:="http://tempuri.org/ISpectron/transpose_dataResponse")>  _
        Sub transpose_data()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISpectron/write_to_653x", ReplyAction:="http://tempuri.org/ISpectron/write_to_653xResponse")>  _
        Function write_to_653x(ByVal taskHandle As System.IntPtr) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISpectron/release_data", ReplyAction:="http://tempuri.org/ISpectron/release_dataResponse")>  _
        Sub release_data(ByVal taskHandle As System.IntPtr)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISpectron/insert_linear_ramp", ReplyAction:="http://tempuri.org/ISpectron/insert_linear_rampResponse")>  _
        Sub insert_linear_ramp(ByVal t_start As Double, ByVal t_stop As Double, ByVal y_start As Double, ByVal y_stop As Double, ByVal dat_chan As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISpectron/insert_sine", ReplyAction:="http://tempuri.org/ISpectron/insert_sineResponse")>  _
        Sub insert_sine(ByVal t_start As Double, ByVal t_stop As Double, ByVal amp As Double, ByVal freq As Double, ByVal offset As Double, ByVal dat_chan As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISpectron/Add", ReplyAction:="http://tempuri.org/ISpectron/AddResponse")>  _
        Function Add(ByVal n1 As Double, ByVal n2 As Double) As Double
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ISpectronChannel
        Inherits SpectronServiceReference.ISpectron, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SpectronClient
        Inherits System.ServiceModel.ClientBase(Of SpectronServiceReference.ISpectron)
        Implements SpectronServiceReference.ISpectron
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function configure_653x(ByVal deviceName As String, ByVal trigger As String, ByVal clock As String, ByVal total_cycles As Integer) As System.IntPtr Implements SpectronServiceReference.ISpectron.configure_653x
            Return MyBase.Channel.configure_653x(deviceName, trigger, clock, total_cycles)
        End Function
        
        Public Sub initialize_data(ByVal total_cycles As Integer) Implements SpectronServiceReference.ISpectron.initialize_data
            MyBase.Channel.initialize_data(total_cycles)
        End Sub
        
        Public Sub transpose_data() Implements SpectronServiceReference.ISpectron.transpose_data
            MyBase.Channel.transpose_data
        End Sub
        
        Public Function write_to_653x(ByVal taskHandle As System.IntPtr) As Integer Implements SpectronServiceReference.ISpectron.write_to_653x
            Return MyBase.Channel.write_to_653x(taskHandle)
        End Function
        
        Public Sub release_data(ByVal taskHandle As System.IntPtr) Implements SpectronServiceReference.ISpectron.release_data
            MyBase.Channel.release_data(taskHandle)
        End Sub
        
        Public Sub insert_linear_ramp(ByVal t_start As Double, ByVal t_stop As Double, ByVal y_start As Double, ByVal y_stop As Double, ByVal dat_chan As Integer) Implements SpectronServiceReference.ISpectron.insert_linear_ramp
            MyBase.Channel.insert_linear_ramp(t_start, t_stop, y_start, y_stop, dat_chan)
        End Sub
        
        Public Sub insert_sine(ByVal t_start As Double, ByVal t_stop As Double, ByVal amp As Double, ByVal freq As Double, ByVal offset As Double, ByVal dat_chan As Integer) Implements SpectronServiceReference.ISpectron.insert_sine
            MyBase.Channel.insert_sine(t_start, t_stop, amp, freq, offset, dat_chan)
        End Sub
        
        Public Function Add(ByVal n1 As Double, ByVal n2 As Double) As Double Implements SpectronServiceReference.ISpectron.Add
            Return MyBase.Channel.Add(n1, n2)
        End Function
    End Class
End Namespace
